name: polaris
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ddO6UritpS
      - POSTGRES_DB=platform
      - PGDATA=/var/lib/postgresql/data/pgdata/
    volumes:
      - ./volumes/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres-db-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@polaris.com"
      PGADMIN_DEFAULT_PASSWORD: "Pi3wEYoqV1"
    ports:
      - 16543:80
    volumes:
      - ./postgresql/servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network

networks:
  postgres-db-network:
    driver: bridge
